# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# https://doc.scrapy.org/en/latest/topics/items.html

import scrapy


class BitautoCarItem(scrapy.Item):

    brand = scrapy.Field()  # 品牌 华晨宝马
    brandmodel = scrapy.Field()  # 车型 宝马x3
    url = scrapy.Field()
    version = scrapy.Field()
    price = scrapy.Field()   # 厂商指导价 39.98w
    year = scrapy.Field()  # 上市年份 2018
    modellevel = scrapy.Field()  # 车型级别 中型suv
    bodytype = scrapy.Field()  # 车身型式 SUV
    powertype = scrapy.Field()  # 动力类型 汽油
    gearboxtype = scrapy.Field()  # 变速箱类型 手自一体
    fuelconsumption = scrapy.Field()  # 混合工况油耗 7.9
    jiasushijian = scrapy.Field()  # 加速时间
    maximumspeed = scrapy.Field()  # 最高车速
    huanbao = scrapy.Field()  # 环保标准
    baoxiuzhengce = scrapy.Field()  # 保修政策
    color = scrapy.Field()  # 外观颜色
    fadongjipailie = scrapy.Field()  # 直列
    gangshu = scrapy.Field()  # 四缸
    zuidaxuhanglicheng = scrapy.Field()  # 最大续航里程 电
    dianchichongdianman = scrapy.Field()  # 电池充电慢
    dianchichongdiankuai = scrapy.Field()  # 电池充电快
    dianchibaoxiu = scrapy.Field()
    butie = scrapy.Field()  # 补贴 电结束 基本信息结束
    clength = scrapy.Field()  # 长宽高，为了清楚表示，加了前缀c
    cwidth = scrapy.Field()  # 长宽高，为了清楚表示，加了前缀c
    cheight = scrapy.Field()  # 长宽高，为了清楚表示，加了前缀c
    wheelbase = scrapy.Field()  # 轴距 2864
    quaility = scrapy.Field()
    seats = scrapy.Field()  # 座位数 5
    xinglixiangrongjimin = scrapy.Field()
    xinglixiangrongjimax = scrapy.Field()
    youxiang = scrapy.Field()
    qianluntai = scrapy.Field()
    houluntai = scrapy.Field()
    beitai = scrapy.Field()
    zuixiaozhuanwanzhijing = scrapy.Field()  # 最小转弯直径
    xitongzonghekw = scrapy.Field()  # 系统综合功率
    xitongzonghenm = scrapy.Field()  # 系统综合扭矩
    lidijianxi = scrapy.Field()  # 车身尺寸完
    aspiration = scrapy.Field()  # 吸气方式 涡轮增压
    displacement = scrapy.Field()  # 排量 1998
    maximumpower = scrapy.Field()  # 最大功率 135
    zuidamali = scrapy.Field()  # 最大马力
    zuidagonglvrpm = scrapy.Field()  # 最大功率转速
    maximumtorque = scrapy.Field()  # 最大扭矩 290
    zuidaniujurpm = scrapy.Field()  # 最大扭矩转速
    gongyou = scrapy.Field()  # 供油方式
    ranyou = scrapy.Field()  # 燃油标号
    fadongjiqiting = scrapy.Field()  # 发动机启停
    gears = scrapy.Field()  # 档位个数 8
    diandongjikw = scrapy.Field()  # 电开始
    diandongjiniuju = scrapy.Field()
    houdiandongjikw = scrapy.Field()
    houdiandongjinm = scrapy.Field()
    dianchirongliang = scrapy.Field()
    haodianliang = scrapy.Field()  # 电结束 动力系统结束
    drivemode = scrapy.Field()  # 驱动方式 全时四驱
    frontsuspensiontype = scrapy.Field()  # 前悬架类型 麦弗逊式独立悬架
    rearsuspensiontype = scrapy.Field()  # 后悬架类型 多连杆式独立悬架
    ketiaoxuanjia = scrapy.Field()  # 可调悬架
    qianlunzhidong = scrapy.Field()  # 前轮制动器类型
    houlunzhidong = scrapy.Field()  # 后轮制动器类型
    zhuchezhidong = scrapy.Field()  # 驻车制动类型
    carbodystructure = scrapy.Field()  # 车体结构 承载式
    chasusuo = scrapy.Field()  # 限滑差速器/差速锁
    jiejinjiao = scrapy.Field()  # 接近角
    liqujiao = scrapy.Field()  # 离去角
    zuidasheshuishendu = scrapy.Field()   # 最大涉水深度
    tongguojiao = scrapy.Field()   # 底盘制动结束
    abs = scrapy.Field()  # 安全配置开始
    ebd = scrapy.Field()
    eba = scrapy.Field()
    ars = scrapy.Field()
    esp = scrapy.Field()
    zhuqinang = scrapy.Field()
    fuqinang = scrapy.Field()
    qianqinang = scrapy.Field()
    houqinang = scrapy.Field()
    ceqilian = scrapy.Field()
    xiqinang = scrapy.Field()
    anquandai = scrapy.Field()
    houpaiqinang = scrapy.Field()
    taiya = scrapy.Field()
    lingtaiya = scrapy.Field()
    ertongzuo = scrapy.Field()  # 安全配置结束
    dingsu = scrapy.Field()  # 驾驶辅助开始
    chedao = scrapy.Field()  # 之后有没有并线辅助？
    pengzhuang = scrapy.Field()
    pilao = scrapy.Field()
    automaticparking = scrapy.Field()  # 自动泊车 o
    yaokong = scrapy.Field()
    automaticdrivingassitance = scrapy.Field()  # 自动驾驶辅助 -
    zhuche = scrapy.Field()
    shangpo = scrapy.Field()
    doupo = scrapy.Field()
    yeshi = scrapy.Field()
    kebianchibi = scrapy.Field()
    qianleida = scrapy.Field()
    houleida = scrapy.Field()
    daocheyingxiang = scrapy.Field()
    jiashimoshi = scrapy.Field()
    bingxianfuzhu = scrapy.Field()  # 驾驶辅助结束
    qiandadeng = scrapy.Field()  # 外部配置开始
    led = scrapy.Field()
    zidongdadeng = scrapy.Field()
    qianwudeng = scrapy.Field()
    dadeng = scrapy.Field()
    tianchuang = scrapy.Field()
    qianchechuang = scrapy.Field()
    houchechuang = scrapy.Field()
    waihoushijing = scrapy.Field()
    neihoushijing = scrapy.Field()
    waihoushijingxuanmu = scrapy.Field()
    yinsi = scrapy.Field()
    houpai = scrapy.Field()
    houzheyang = scrapy.Field()
    qianyushua = scrapy.Field()
    houyushua = scrapy.Field()
    dianximen = scrapy.Field()
    diandongcehua = scrapy.Field()
    diandongxingli = scrapy.Field()
    chedingxinglijia = scrapy.Field()
    zhongkongsuo = scrapy.Field()
    zhinengyaoshi = scrapy.Field()
    yuanchengyaokong = scrapy.Field()
    weiyi = scrapy.Field()
    yundongwaiguan = scrapy.Field()
    liumeiti = scrapy.Field()  # 外部配置结束
    neishi = scrapy.Field()  # 内部配置开始
    fenweideng = scrapy.Field()
    zheyangban = scrapy.Field()
    fangxiangpan = scrapy.Field()
    duogongnengfxp = scrapy.Field()
    fxptiaojie = scrapy.Field()
    fxpjiare = scrapy.Field()
    fxphuandang = scrapy.Field()
    qianpaikongtiao = scrapy.Field()
    houpaikongtiao = scrapy.Field()
    xiangfen = scrapy.Field()
    kongqijinghua = scrapy.Field()
    chezaibingxiang = scrapy.Field()
    zhudongjiangzao = scrapy.Field()  # 内部配置结束
    zuoyicaizhi = scrapy.Field()   # 座椅配置开始
    yundongfenggezuoyi = scrapy.Field()
    zhuzuoyi = scrapy.Field()
    fuzuoyi = scrapy.Field()
    zhutiaojie = scrapy.Field()
    futiaojie = scrapy.Field()
    dierpai1 = scrapy.Field()
    dierpai2 = scrapy.Field()
    qianpaizuoyi = scrapy.Field()
    houpaizuoyi = scrapy.Field()
    qianpaizhongyang = scrapy.Field()
    houpaizhongyang = scrapy.Field()
    disanpai = scrapy.Field()
    zuoyifangdao = scrapy.Field()
    houpaibeijia = scrapy.Field()
    houpaizhedie = scrapy.Field()  # 座椅配置结束
    zhongkongcaise = scrapy.Field()  # 信息娱乐开始
    yejingping = scrapy.Field()
    quanyejing = scrapy.Field()
    xingchediannao = scrapy.Field()
    hud = scrapy.Field()
    gps = scrapy.Field()
    zhinenghulian = scrapy.Field()
    viocecontrol = scrapy.Field()  # 语音控制 o
    mobileinternet = scrapy.Field()  # 手机互联 carplay
    shoujiwuxian = scrapy.Field()
    shoushikongzhi = scrapy.Field()
    cd = scrapy.Field()
    bluetoothwifi = scrapy.Field()  # 蓝牙wifi 蓝牙
    waijie = scrapy.Field()
    chezaixingche = scrapy.Field()
    chezaidianshi = scrapy.Field()
    audiobrand = scrapy.Field()  # 音响品牌 -
    yangshengqi = scrapy.Field()
    houpaiyejingping = scrapy.Field()
    chezai220 = scrapy.Field()  # 信息娱乐结束
    marketyear = scrapy.Field()  # 上市年份
    marketmonth = scrapy.Field()  # 上市月份
    marketday = scrapy.Field()  # 上市日期
    zaichan = scrapy.Field()  # 在产
    zaixiao = scrapy.Field()  # 在销
